### ISSUE TITLE
"Images" test seems to not do the same thing in Safari as other browsers

### ISSUE THREAD

**Issue by bgrins** [WebKit/MotionMark#19]
Here's a screenshot with Firefox on left, Safari on right - loading https://browserbench.org/MotionMark1.2/developer.html?warmup-length=2000&warmup-frame-count=30&first-frame-minimum-length=0&test-interval=30&display=minimal&tiles=big&controller=ramp&frame-rate=50&time-measurement=performance&suite-name=MotionMark&test-name=Images

Firefox has some kind of fade out / dithering effect for the images when they disappear that does not appear to happen in Safari. Chrome's behavior matches Firefox.

https://github.com/WebKit/MotionMark/assets/95570/d2bd1457-4b7c-4cc6-aa8b-6fb445f1f6f9

**Comment by smfr** [comment]
Should be fixed in WebKit trunk. Please test in Safari Tech Preview, or a macOS Sonoma beta build. The fix may be https://commits.webkit.org/265712@main or a related commit.
