### ISSUE TITLE
Add an index.html to the root with a redirect to MotionMark1.2/

### ISSUE THREAD

**Issue by bgrins** [WebKit/MotionMark#2]
It would be helpful to have an index.html file at the root in order to host the repo using a static file server. Rather than needing to create some kind of home page, could we add an empty html file with something that redirects to the latest version like `<meta http-equiv="Refresh" content="0; URL=./MotionMark1.2/" />`

**Comment by bgrins** [comment]
I can make a PR if this works for people

**Comment by litherum** [comment]
Sure, sounds good.
