### ISSUE TITLE
MotionMark's multiply suite reaches max complexity on faster devices

### ISSUE THREAD

**Issue by sky2** [WebKit/MotionMark#5]
This is basically the same as https://bugs.webkit.org/show_bug.cgi?id=240605 . More specifically, faster machines may be able to handle max complexity of the multiply suite. This can lead to high variance in the score. Additionally, on120hz displays when requestanimationframe is serviced at 120hz (as happens in chrome) a score of 0 may be given.

**Comment by smfr** [comment]
The fix was merged in https://github.com/WebKit/MotionMark/commit/f5d127cff37d174599ab4e954a6ebfbb7787aeb8
